spring:
  data:
    mongodb:
      database: ${SPRING_DATA_SOURCE_NAME:mongo_project}
      uri: ${SPRING_DATA_SOURCE_URI:mongodb://root:password@localhost:27017}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER