spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      database: ${SPRING_DATA_SOURCE_NAME}
      uri: ${SPRING_DATA_SOURCE_URI}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER