spring:
  data:
    mongodb:
      database: ${SPRING_DATA_SOURCE_NAME:jobs}
      uri: ${SPRING_DATA_SOURCE_URI:mongodb://root:password@localhost:27017}
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER