networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: api_Student_project
    networks:
      - app-network
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - '8080:8080'
    environment:
      SPRING_DATA_SOURCE_URI: ${DATA_SOURCE_URI}

  mongo:
    image: mongo:6.0.6-jammy
    container_name: mongo
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db