networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: pasteApi_project
    networks:
      - app-network
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '8080:8080'
    environment:
      DATABASE_HOST: postgres

  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_USERNAME}
      POSTGRES_DB: ${DATASOURCE_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data