networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
    container_name: spring_security_system_project
    networks:
      - app-network
    ports:
      - '8080:8080'