spring:
  config:
    import: optional:file:API_Student/.env[.properties]
  data:
    mongodb:
      database: ${SPRING_DATA_SOURCE_NAME}
      uri: ${SPRING_DATA_SOURCE_URI}
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER